// Auto-generated by build-preloads.js from the _meta of every *.json in this folder.
// A translation pack made without node can add its own line by hand.
window._i18nLanguages = [
    {"code":"en","name":"English"},
    {"code":"de","name":"Deutsch"},
    {"code":"es","name":"Español"},
    {"code":"fr","name":"French"},
    {"code":"it","name":"Italiano"},
    {"code":"ja","name":"日本語"},
    {"code":"ko","name":"한국어"},
    {"code":"pl","name":"Polski"},
    {"code":"pt-br","name":"Português (Brasil)"},
    {"code":"ru","name":"Русский"},
    {"code":"tr","name":"Türkçe"},
    {"code":"zh-cn","name":"简体中文"},
    {"code":"zh-tw","name":"繁體中文"}
];
